import Head from 'next/head';

import Menu from 'components/Menu';
import Footer from 'components/Footer';
import { ChildrenProps } from 'types/Base';

const Base = ({ children }: ChildrenProps) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />
      {children}
      <Footer />
    </>
  );
};

export default Base;
