import Head from 'next/head';
import { GetStaticProps } from 'next';

import { getPhotos } from 'service/photos';

interface Props {
  total_results: number;
  per_page: number;
  page: number;
  photos: [];
}

interface Photo {
  id: number;
  photographer_url: string;
  src: {
    original: string;
    small: string;
  };
}

export default function Home(props: Props) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {props.photos.map((photo: Photo, index) => (
        <img key={index} src={photo.src.small} />
      ))}
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const responses = await getPhotos();

  return {
    props: {
      ...responses
    }
  };
};
