import Head from 'next/head';
import { GetStaticProps } from 'next';

import Card from 'components/Card';
import Logo from 'components/Logo';
import { Container } from 'styles/container';

import { getPhotos } from 'service/photos';

interface Props {
  total_results: number;
  per_page: number;
  page: number;
  photos: [];
}

interface Photo {
  id: number;
  photographer_url: string;
  src: {
    original: string;
    small: string;
    large: string;
  };
}

export default function Home(props: Props) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Logo />
        <a href="/page">Go to pages</a>
        {props.photos.map((photo: Photo) => (
          <Card key={photo.id} src={photo.src.large} />
        ))}
      </Container>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const responses = await getPhotos();

  return {
    props: {
      ...responses
    }
  };
};
